name: IMAGE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/arm64

    steps:
      - uses: actions/checkout@v2

      # Configuração do .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Install dependencies
        run: dotnet restore WebApiTest/WebApiTest/WebApiTest.csproj

      # Envio da imagem para o Registry da OCI
      - name: Build
        run: |
          dotnet build WebApiTest/WebApiTest/WebApiTest.csproj -c Release -o out

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3.7.1

      # Configurar QEMU para emulação ARM
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Try install QEMU ARM emulator
        run: |
          docker buildx ls

      - name: Login to OCI
        uses: docker/login-action@v3.3.0
        with:
          registry: sa-saopaulo-1.ocir.io
          username: ${{ secrets.OCI_USERNAME }}
          password: ${{ secrets.OCI_AUTH_TOKEN }}
      
      - name: Push docker image to OCI
        uses: docker/build-push-action@v6.10.0
        with:
          context: ./WebApiTest
          platforms: linux/arm64
          tags: |
            sa-saopaulo-1.ocir.io/${{ secrets.OCI_TENANCY_NAMESPACE }}/oci-demo:${{ github.run_number }}
            sa-saopaulo-1.ocir.io/${{ secrets.OCI_TENANCY_NAMESPACE }}/oci-demo:latest
          push: true
          file: ./WebApiTest/WebApiTest/_ARM_Dockerfile

      # - name: Build Docker image
      #   run: |
      #     docker build \
      #       -f WebApiTest/WebApiTest/Dockerfile \
      #       -t sa-saopaulo-1.ocir.io/${{ secrets.OCI_TENANCY_NAMESPACE }}/oci-demo:${GITHUB_RUN_NUMBER} WebApiTest/.

  