name: CI

on:
  workflow_dispatch:
    
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        
        # Configuração do .NET
        - name: Set up .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 8.0.x
        
        - name: Install dependencies
          run: dotnet restore WebApiTest/WebApiTest/WebApiTest.csproj

        # Envio da imagem para o Registry da OCI
        - name: Build
          run: |
            dotnet build WebApiTest/WebApiTest/WebApiTest.csproj -c Release -o out

        # consultar a url: "https://docs.oracle.com/pt-br/iaas/Content/Registry/Concepts/registryprerequisites.htm#regional-availability" 
        # para saber qual a URL do Registry da OCI para a região que você está utilizando
        - name: Build Docker image
          run: |            
            docker build -f WebApiTest/WebApiTest/Dockerfile -t sa-saopaulo-1.ocir.io/${{ secrets.OCI_TENANCY_NAMESPACE }}/oci-demo:latest WebApiTest/.

        - name: Login to OCI
          run: |
            echo "${{ secrets.OCI_AUTH_TOKEN }}" | docker login sa-saopaulo-1.ocir.io -u '${{ secrets.OCI_TENANCY_NAMESPACE }}/jeferson.m.bruno@gmail.com' --password-stdin 

        - name: Push docker image to OCI
          run: |
            docker push sa-saopaulo-1.ocir.io/${{ secrets.OCI_TENANCY_NAMESPACE }}/oci-demo:latest